export type HighlightMode = "word-highlight" | "word-pop" | "underline-sweep" | "pill-glow" | "karaoke-fill";
export type BackgroundMode = "none" | "pill" | "box" | "glass";
export type TemplateCategory = "minimal" | "bold" | "neon" | "outline" | "karaoke" | "classic";

export interface CaptionStylePack {
  id: string;
  name: string;
  category: TemplateCategory;
  fontFamily: string;
  fontWeight: number;
  fontSize: number;
  textTransform: "none" | "uppercase" | "lowercase" | "capitalize";
  textColor: string;
  activeColor: string;
  inactiveColor: string;
  strokeColor: string;
  strokeWidth: number;
  shadow: string;
  backgroundMode: BackgroundMode;
  backgroundColor: string;
  highlightMode: HighlightMode;
  wordSpacing: number;
  lineHeight: number;
  letterSpacing: number;
}

export const captionStylePacks: Record<string, CaptionStylePack> = {
  "opus-clean": {
    id: "opus-clean",
    name: "Opus Clean",
    category: "minimal",
    fontFamily: "'Inter', sans-serif",
    fontWeight: 700,
    fontSize: 42,
    textTransform: "none",
    textColor: "#FFFFFF",
    activeColor: "#FFFFFF",
    inactiveColor: "rgba(255,255,255,0.45)",
    strokeColor: "#000000",
    strokeWidth: 0,
    shadow: "0 2px 8px rgba(0,0,0,0.6)",
    backgroundMode: "none",
    backgroundColor: "transparent",
    highlightMode: "word-highlight",
    wordSpacing: 6,
    lineHeight: 1.25,
    letterSpacing: -0.5,
  },
  "bold-pop": {
    id: "bold-pop",
    name: "Bold Pop",
    category: "bold",
    fontFamily: "'Inter', sans-serif",
    fontWeight: 900,
    fontSize: 48,
    textTransform: "uppercase",
    textColor: "#FFFFFF",
    activeColor: "#FACC15",
    inactiveColor: "rgba(255,255,255,0.35)",
    strokeColor: "#000000",
    strokeWidth: 3,
    shadow: "0 4px 16px rgba(0,0,0,0.7)",
    backgroundMode: "none",
    backgroundColor: "transparent",
    highlightMode: "word-pop",
    wordSpacing: 8,
    lineHeight: 1.2,
    letterSpacing: 1,
  },
  "karaoke-underline": {
    id: "karaoke-underline",
    name: "Karaoke Underline",
    category: "karaoke",
    fontFamily: "'Inter', sans-serif",
    fontWeight: 700,
    fontSize: 40,
    textTransform: "none",
    textColor: "#FFFFFF",
    activeColor: "#3B82F6",
    inactiveColor: "rgba(255,255,255,0.5)",
    strokeColor: "transparent",
    strokeWidth: 0,
    shadow: "0 2px 12px rgba(0,0,0,0.5)",
    backgroundMode: "none",
    backgroundColor: "transparent",
    highlightMode: "underline-sweep",
    wordSpacing: 6,
    lineHeight: 1.35,
    letterSpacing: 0,
  },
  "glass-pill": {
    id: "glass-pill",
    name: "Glass Pill",
    category: "minimal",
    fontFamily: "'Inter', sans-serif",
    fontWeight: 600,
    fontSize: 36,
    textTransform: "none",
    textColor: "#FFFFFF",
    activeColor: "#FFFFFF",
    inactiveColor: "rgba(255,255,255,0.6)",
    strokeColor: "transparent",
    strokeWidth: 0,
    shadow: "0 2px 6px rgba(0,0,0,0.3)",
    backgroundMode: "glass",
    backgroundColor: "rgba(0,0,0,0.4)",
    highlightMode: "pill-glow",
    wordSpacing: 6,
    lineHeight: 1.3,
    letterSpacing: 0,
  },
  "minimal-lower": {
    id: "minimal-lower",
    name: "Minimal Lower Third",
    category: "classic",
    fontFamily: "'Inter', sans-serif",
    fontWeight: 500,
    fontSize: 32,
    textTransform: "none",
    textColor: "#FFFFFF",
    activeColor: "#FFFFFF",
    inactiveColor: "rgba(255,255,255,0.7)",
    strokeColor: "transparent",
    strokeWidth: 0,
    shadow: "0 1px 4px rgba(0,0,0,0.4)",
    backgroundMode: "box",
    backgroundColor: "rgba(0,0,0,0.55)",
    highlightMode: "word-highlight",
    wordSpacing: 5,
    lineHeight: 1.3,
    letterSpacing: 0.3,
  },
  "high-contrast": {
    id: "high-contrast",
    name: "High Contrast",
    category: "bold",
    fontFamily: "'Inter', sans-serif",
    fontWeight: 900,
    fontSize: 46,
    textTransform: "uppercase",
    textColor: "#FFFFFF",
    activeColor: "#FF3B30",
    inactiveColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 4,
    shadow: "0 0 0 transparent",
    backgroundMode: "none",
    backgroundColor: "transparent",
    highlightMode: "word-pop",
    wordSpacing: 8,
    lineHeight: 1.15,
    letterSpacing: 2,
  },
  "soft-gradient": {
    id: "soft-gradient",
    name: "Soft Gradient",
    category: "minimal",
    fontFamily: "'Inter', sans-serif",
    fontWeight: 600,
    fontSize: 38,
    textTransform: "none",
    textColor: "#E0E7FF",
    activeColor: "#818CF8",
    inactiveColor: "rgba(224,231,255,0.4)",
    strokeColor: "transparent",
    strokeWidth: 0,
    shadow: "0 2px 20px rgba(129,140,248,0.4)",
    backgroundMode: "none",
    backgroundColor: "transparent",
    highlightMode: "word-highlight",
    wordSpacing: 6,
    lineHeight: 1.3,
    letterSpacing: 0,
  },
  "neon-outline": {
    id: "neon-outline",
    name: "Neon Outline",
    category: "neon",
    fontFamily: "'Inter', sans-serif",
    fontWeight: 800,
    fontSize: 44,
    textTransform: "uppercase",
    textColor: "transparent",
    activeColor: "#22D3EE",
    inactiveColor: "rgba(34,211,238,0.3)",
    strokeColor: "#22D3EE",
    strokeWidth: 2,
    shadow: "0 0 20px rgba(34,211,238,0.6), 0 0 40px rgba(34,211,238,0.3)",
    backgroundMode: "none",
    backgroundColor: "transparent",
    highlightMode: "pill-glow",
    wordSpacing: 7,
    lineHeight: 1.2,
    letterSpacing: 1.5,
  },
  "caption-pro": {
    id: "caption-pro",
    name: "Caption Pro",
    category: "karaoke",
    fontFamily: "'Inter', sans-serif",
    fontWeight: 700,
    fontSize: 40,
    textTransform: "none",
    textColor: "#FFFFFF",
    activeColor: "#10B981",
    inactiveColor: "rgba(255,255,255,0.5)",
    strokeColor: "#000000",
    strokeWidth: 1.5,
    shadow: "0 2px 8px rgba(0,0,0,0.5)",
    backgroundMode: "none",
    backgroundColor: "transparent",
    highlightMode: "karaoke-fill",
    wordSpacing: 6,
    lineHeight: 1.25,
    letterSpacing: 0,
  },
  "documentary": {
    id: "documentary",
    name: "Documentary",
    category: "classic",
    fontFamily: "'Georgia', 'Times New Roman', serif",
    fontWeight: 400,
    fontSize: 34,
    textTransform: "none",
    textColor: "#FFFFFF",
    activeColor: "#FBBF24",
    inactiveColor: "rgba(255,255,255,0.65)",
    strokeColor: "transparent",
    strokeWidth: 0,
    shadow: "0 1px 6px rgba(0,0,0,0.5)",
    backgroundMode: "box",
    backgroundColor: "rgba(0,0,0,0.6)",
    highlightMode: "word-highlight",
    wordSpacing: 5,
    lineHeight: 1.4,
    letterSpacing: 0.5,
  },
  "tiktok-viral": {
    id: "tiktok-viral",
    name: "TikTok Viral",
    category: "bold",
    fontFamily: "'Inter', sans-serif",
    fontWeight: 900,
    fontSize: 50,
    textTransform: "uppercase",
    textColor: "#FFFFFF",
    activeColor: "#FF006E",
    inactiveColor: "rgba(255,255,255,0.3)",
    strokeColor: "#000000",
    strokeWidth: 3,
    shadow: "0 4px 16px rgba(255,0,110,0.4)",
    backgroundMode: "none",
    backgroundColor: "transparent",
    highlightMode: "word-pop",
    wordSpacing: 8,
    lineHeight: 1.15,
    letterSpacing: 1,
  },
  "luxury": {
    id: "luxury",
    name: "Luxury",
    category: "classic",
    fontFamily: "'Georgia', serif",
    fontWeight: 700,
    fontSize: 36,
    textTransform: "none",
    textColor: "#F5E6D3",
    activeColor: "#D4AF37",
    inactiveColor: "rgba(245,230,211,0.4)",
    strokeColor: "transparent",
    strokeWidth: 0,
    shadow: "0 2px 12px rgba(212,175,55,0.3)",
    backgroundMode: "none",
    backgroundColor: "transparent",
    highlightMode: "karaoke-fill",
    wordSpacing: 7,
    lineHeight: 1.35,
    letterSpacing: 2,
  },
  "neon-pink": {
    id: "neon-pink",
    name: "Neon Pink",
    category: "neon",
    fontFamily: "'Inter', sans-serif",
    fontWeight: 800,
    fontSize: 44,
    textTransform: "uppercase",
    textColor: "#FF69B4",
    activeColor: "#FF1493",
    inactiveColor: "rgba(255,105,180,0.3)",
    strokeColor: "#FF69B4",
    strokeWidth: 2,
    shadow: "0 0 20px rgba(255,20,147,0.6), 0 0 40px rgba(255,20,147,0.3)",
    backgroundMode: "none",
    backgroundColor: "transparent",
    highlightMode: "pill-glow",
    wordSpacing: 7,
    lineHeight: 1.2,
    letterSpacing: 1,
  },
  "subtitle-bar": {
    id: "subtitle-bar",
    name: "Subtitle Bar",
    category: "classic",
    fontFamily: "'Inter', sans-serif",
    fontWeight: 600,
    fontSize: 34,
    textTransform: "none",
    textColor: "#FFFFFF",
    activeColor: "#FFFFFF",
    inactiveColor: "rgba(255,255,255,0.8)",
    strokeColor: "transparent",
    strokeWidth: 0,
    shadow: "none",
    backgroundMode: "pill",
    backgroundColor: "rgba(0,0,0,0.7)",
    highlightMode: "word-highlight",
    wordSpacing: 5,
    lineHeight: 1.3,
    letterSpacing: 0.2,
  },
  "marker-highlight": {
    id: "marker-highlight",
    name: "Marker Highlight",
    category: "bold",
    fontFamily: "'Inter', sans-serif",
    fontWeight: 800,
    fontSize: 44,
    textTransform: "none",
    textColor: "#000000",
    activeColor: "#000000",
    inactiveColor: "rgba(0,0,0,0.4)",
    strokeColor: "transparent",
    strokeWidth: 0,
    shadow: "none",
    backgroundMode: "pill",
    backgroundColor: "#FACC15",
    highlightMode: "word-pop",
    wordSpacing: 6,
    lineHeight: 1.25,
    letterSpacing: 0,
  },
  "kinetic-scale": {
    id: "kinetic-scale",
    name: "Kinetic Scale",
    category: "bold",
    fontFamily: "'Inter', sans-serif",
    fontWeight: 900,
    fontSize: 52,
    textTransform: "uppercase",
    textColor: "#FFFFFF",
    activeColor: "#F97316",
    inactiveColor: "rgba(255,255,255,0.25)",
    strokeColor: "#000000",
    strokeWidth: 3,
    shadow: "0 4px 20px rgba(0,0,0,0.8)",
    backgroundMode: "none",
    backgroundColor: "transparent",
    highlightMode: "word-pop",
    wordSpacing: 10,
    lineHeight: 1.1,
    letterSpacing: 2,
  },
};

captionStylePacks["default"] = captionStylePacks["opus-clean"];

export const colorPresetFilters: Record<string, string> = {
  none: "none",
  warm: "sepia(0.3) saturate(1.3) brightness(1.05)",
  cool: "saturate(0.8) hue-rotate(20deg) brightness(1.05)",
  vintage: "sepia(0.5) contrast(1.1) brightness(0.95) saturate(0.8)",
  noir: "grayscale(1) contrast(1.3) brightness(0.9)",
  vivid: "saturate(1.6) contrast(1.15) brightness(1.05)",
};
