[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x", "chromium", "nss", "alsa-lib", "at-spi2-atk", "libdrm", "mesa", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXrandr", "xorg.libXfixes", "libxkbcommon", "pango", "cairo", "cups"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:prod"
